### ISSUE TITLE
General Icons folder missing most of the icons

### ISSUE THREAD

**Issue by AdrianSimionov** [m-radzikowski/omnigraffle-stencil#3]
For whatever reason, the general Icons folder ended up having only 2 icons inside the Stencil.

Possible issues:
- the icons did not exist when you generate it
- a bug into the script

**Comment by m-radzikowski** [comment]
Hey. This tool is not just for the AWS icons, it can be used to generate stencil from any icons. AWS changes directories structure in almost every new release, so it may require changing params when running the tool.

I've updated the readme, explaining how to generate stencil for the latest (2021-01-21) AWS icons. Also, I've uploaded a stencil to Stenciltown: https://stenciltown.omnigroup.com/stencils/aws-2021-01-31-all/

Let me know if that does not explains everything and you have more questions/problems.
